### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dwd010** [ayaan1005/Alix-Beta#9]
Hi look at my error
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'discord.js'
Require stack:
- /home/runner/Alix-Beta/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/Alix-Beta/index.js:1:32)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/Alix-Beta/index.js' ]
}

**Comment by Ayaan-GuitarHost** [comment]
discord.js Module Not Found Just Try Running this commands in terminal

npm i
npm i discord.js

**Comment by Ayaan-Dev** [comment]
> Hi look at my error
> internal/modules/cjs/loader.js:818
> throw err;
> ^
> 
> Error: Cannot find module 'discord.js'
> Require stack:
> 
> * /home/runner/Alix-Beta/index.js
>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
>   at Function.Module._load (internal/modules/cjs/loader.js:667:27)
>   at Module.require (internal/modules/cjs/loader.js:887:19)
>   at require (internal/modules/cjs/helpers.js:74:18)
>   at Object. (/home/runner/Alix-Beta/index.js:1:32)
>   at Module._compile (internal/modules/cjs/loader.js:999:30)
>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
>   at Module.load (internal/modules/cjs/loader.js:863:32)
>   at Function.Module._load (internal/modules/cjs/loader.js:708:14)
>   at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/home/runner/Alix-Beta/index.js' ]
>   }

discord.js Module Not Found Just Try Running this commands in terminal

`npm i`
`npm i discord.js`
